//! Anti-hallucination validation of a narrator draft. Two checks, per the
//! architecture: every `reference` must be one of the supplied events, and every
//! proper noun in the body must be a real world name (present in the closed
//! `ner_lexicon`). Names are deterministic, so the lexicon is exact.
//!
//! Proper-noun detection without an NLP model is heuristic: a capitalized,
//! alphabetic token is treated as a name unless it's a common English word
//! (`STOPWORDS`) or a token of some lexicon name. That can false-positive on an
//! unusual capitalized common word — which only costs a retry and then the
//! (always-valid) template fallback, never a crash. The stoplist is broad by
//! intent and meant to be refined against real model output once narrating live.

use std::collections::BTreeSet;

use mapgen_core::{EventId, WorldData};
use mapgen_history::lore_api::ner_lexicon;

use crate::schema::ChronicleDraft;

/// Validate a draft against the world. `slice` is the set of events supplied to
/// the narrator (its `references` must be drawn from these). Returns a
/// human-readable violation on failure (fed back into the retry prompt).
pub fn validate(
    draft: &ChronicleDraft,
    world: &WorldData,
    slice: &[EventId],
) -> Result<(), String> {
    let supplied: BTreeSet<u32> = slice.iter().map(|e| e.0).collect();
    for &r in &draft.references {
        if !supplied.contains(&r) {
            return Err(format!(
                "cited event [{r}] was not among the supplied events"
            ));
        }
    }

    // Decompose every lexicon name with the *same* tokenizer used on the prose
    // (split on whitespace + name-joining separators, trim punctuation), so a
    // multi-word or hyphenated name validates piece-by-piece and the allowed set
    // can't drift from the body side.
    let lexicon = ner_lexicon(world);
    let allowed: BTreeSet<&str> = lexicon.iter().flat_map(|n| name_pieces(n)).collect();

    // Both the body *and the title* must be grounded — a hallucinated name in the
    // title is shown to the user just the same.
    check_grounded(&draft.title, &allowed).map_err(|w| {
        format!("title names \"{w}\", which is not in the supplied world context (possible hallucination)")
    })?;
    check_grounded(&draft.body, &allowed).map_err(|w| {
        format!("body names \"{w}\", which is not in the supplied world context (possible hallucination)")
    })?;
    Ok(())
}

/// Every proper-noun candidate in `text` must be an allowed name token or a
/// common word. On the first violation, `Err(token)`.
fn check_grounded(text: &str, allowed: &BTreeSet<&str>) -> Result<(), String> {
    for w in name_pieces(text) {
        let first = w.chars().next().expect("name_pieces yields non-empty");
        // A proper-noun candidate is capitalized and contains a letter (so pure
        // numbers — e.g. a year — are not treated as names here). A lone letter
        // (an initial, a placeholder) is not a name.
        if !first.is_uppercase() || !w.chars().any(|c| c.is_alphabetic()) || w.chars().count() == 1
        {
            continue;
        }
        if allowed.contains(w) || STOPWORDS.contains(&w.to_lowercase().as_str()) {
            continue;
        }
        return Err(w.to_string());
    }
    Ok(())
}

/// Split text into name "pieces": break on whitespace **and** on the separators
/// that join names (hyphen, en/em dash, slash), strip a trailing possessive
/// (ASCII `'s` or curly `’s`) and surrounding punctuation. Yields non-empty
/// pieces. Using this on both the lexicon and the prose closes the bypasses
/// where `Zxq-Wbb`, `R2dax`, or `Foo’s` slipped through the old all-alphabetic
/// gate.
fn name_pieces(text: &str) -> impl Iterator<Item = &str> {
    text.split(|c: char| c.is_whitespace() || matches!(c, '-' | '\u{2013}' | '\u{2014}' | '/'))
        .filter_map(strip_piece)
}

fn strip_piece(piece: &str) -> Option<&str> {
    // Keep apostrophes during the first trim so a possessive survives to be
    // stripped, then drop any remaining edge punctuation.
    let w = piece.trim_matches(|c: char| !c.is_alphanumeric() && c != '\'' && c != '\u{2019}');
    let w = w
        .strip_suffix("'s")
        .or_else(|| w.strip_suffix("\u{2019}s"))
        .unwrap_or(w);
    let w = w.trim_matches(|c: char| !c.is_alphanumeric());
    (!w.is_empty()).then_some(w)
}

/// Common English words that legitimately appear capitalized (sentence-initial
/// or otherwise) in chronicle prose, so they aren't mistaken for invented names.
/// Lowercased comparison. Broad by intent — a false negative here would let a
/// hallucination through, but a false *positive* would needlessly reject good
/// prose; still refine against real model output once narrating live.
const STOPWORDS: &[&str] = &[
    // articles / conjunctions / prepositions
    "the",
    "a",
    "an",
    "and",
    "but",
    "or",
    "nor",
    "for",
    "yet",
    "so",
    "of",
    "to",
    "in",
    "on",
    "at",
    "by",
    "with",
    "from",
    "into",
    "onto",
    "unto",
    "upon",
    "over",
    "under",
    "underneath",
    "beneath",
    "above",
    "below",
    "beside",
    "between",
    "among",
    "amongst",
    "amid",
    "amidst",
    "against",
    "through",
    "throughout",
    "during",
    "before",
    "after",
    "since",
    "until",
    "till",
    "while",
    "whilst",
    "as",
    "than",
    "about",
    "across",
    "beyond",
    "within",
    "without",
    "toward",
    "towards",
    "around",
    "near",
    "off",
    "out",
    "up",
    "down",
    "past",
    "per",
    "via",
    "despite",
    "concerning",
    "regarding",
    "betwixt",
    "ere",
    // connectives / sentence-opening adverbs
    "however",
    "therefore",
    "thus",
    "hence",
    "henceforth",
    "thereafter",
    "thereupon",
    "whereupon",
    "whereas",
    "moreover",
    "furthermore",
    "nevertheless",
    "nonetheless",
    "meanwhile",
    "afterward",
    "afterwards",
    "then",
    "now",
    "soon",
    "later",
    "once",
    "again",
    "ever",
    "never",
    "always",
    "often",
    "seldom",
    "hardly",
    "indeed",
    "verily",
    "truly",
    "surely",
    "perhaps",
    "maybe",
    "almost",
    "only",
    "even",
    "also",
    "too",
    "still",
    "here",
    "there",
    "thence",
    "hither",
    "thither",
    "whither",
    "wherein",
    "therein",
    "thereby",
    "thereof",
    "because",
    "although",
    "though",
    "unless",
    "lest",
    "if",
    "when",
    "where",
    "why",
    "how",
    "whence",
    // pronouns / determiners
    "i",
    "it",
    "its",
    "he",
    "him",
    "his",
    "she",
    "her",
    "hers",
    "they",
    "them",
    "their",
    "theirs",
    "we",
    "us",
    "our",
    "ours",
    "you",
    "your",
    "yours",
    "this",
    "that",
    "these",
    "those",
    "such",
    "all",
    "any",
    "both",
    "each",
    "every",
    "few",
    "fewer",
    "more",
    "most",
    "much",
    "many",
    "other",
    "others",
    "another",
    "some",
    "none",
    "no",
    "not",
    "own",
    "same",
    "very",
    "who",
    "whom",
    "whose",
    "which",
    "what",
    "whoever",
    "whatever",
    "whichever",
    "neither",
    "either",
    "whether",
    // verbs / auxiliaries (saga / chronicle sentence-openers)
    "is",
    "was",
    "were",
    "be",
    "been",
    "being",
    "are",
    "am",
    "had",
    "has",
    "have",
    "having",
    "did",
    "do",
    "does",
    "done",
    "can",
    "will",
    "shall",
    "should",
    "would",
    "could",
    "may",
    "might",
    "must",
    "let",
    "came",
    "come",
    "went",
    "go",
    "gone",
    "rose",
    "fell",
    "fall",
    "grew",
    "made",
    "took",
    "gave",
    "held",
    "died",
    "born",
    "bore",
    "slew",
    "slain",
    "fled",
    "sent",
    "set",
    "knew",
    "know",
    "hear",
    "heard",
    "behold",
    "beheld",
    "sing",
    "sang",
    "sung",
    "tell",
    "told",
    "said",
    "saw",
    "see",
    "seen",
    "lo",
    "yea",
    "nay",
    "alas",
    "woe",
    // numerals / ordinals / quantity
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "score",
    "hundred",
    "thousand",
    "first",
    "second",
    "third",
    "fourth",
    "fifth",
    "sixth",
    "seventh",
    "eighth",
    "ninth",
    "tenth",
    "last",
    "latter",
    "former",
    "half",
    // adjectives common to chronicles
    "great",
    "greater",
    "greatest",
    "grand",
    "mighty",
    "dread",
    "dark",
    "darker",
    "holy",
    "sacred",
    "blessed",
    "cursed",
    "old",
    "older",
    "eldest",
    "ancient",
    "young",
    "younger",
    "new",
    "fair",
    "foul",
    "high",
    "low",
    "long",
    "short",
    "vast",
    "deep",
    "wide",
    "golden",
    "iron",
    "bloody",
    "bitter",
    "cruel",
    "noble",
    "royal",
    "true",
    "false",
    "fell",
    // time / era words
    "year",
    "years",
    "age",
    "ages",
    "era",
    "day",
    "days",
    "night",
    "nights",
    "season",
    "winter",
    "summer",
    "spring",
    "autumn",
    "dawn",
    "dusk",
    "morning",
    "evening",
    "century",
    "decade",
    "generation",
    "reign",
    "time",
    "times",
    // recurring domain nouns (capitalized in prose but not names)
    "realm",
    "realms",
    "kingdom",
    "kingdoms",
    "empire",
    "throne",
    "crown",
    "war",
    "wars",
    "battle",
    "battles",
    "siege",
    "sieges",
    "peace",
    "faith",
    "faiths",
    "sect",
    "god",
    "gods",
    "goddess",
    "heaven",
    "hell",
    "beast",
    "beasts",
    "dragon",
    "wyrm",
    "champion",
    "hero",
    "heroes",
    "prophecy",
    "prophet",
    "seer",
    "oracle",
    "dynasty",
    "house",
    "lord",
    "lords",
    "lady",
    "ladies",
    "king",
    "kings",
    "queen",
    "queens",
    "prince",
    "princess",
    "duke",
    "count",
    "baron",
    "saint",
    "father",
    "mother",
    "brother",
    "sister",
    "son",
    "daughter",
    "heir",
    "court",
    "army",
    "host",
    "sword",
    "shield",
    "banner",
    "gate",
    "gates",
    "tower",
    "temple",
    "shrine",
    "altar",
    "relic",
    "artifact",
    "north",
    "south",
    "east",
    "west",
    "land",
    "lands",
    "sea",
    "seas",
    "mountain",
    "mountains",
    "river",
    "rivers",
    "city",
    "cities",
    "town",
    "towns",
    "folk",
    "people",
    "peoples",
    "men",
    "man",
    "woman",
    "women",
    "child",
    "children",
    "kin",
    "blood",
    "line",
    "name",
    "names",
    // narrative / title vocabulary (titles use these as common nouns, not names)
    "account",
    "accounts",
    "lay",
    "lays",
    "saga",
    "sagas",
    "tale",
    "tales",
    "annal",
    "annals",
    "chronicle",
    "chronicles",
    "dispatch",
    "story",
    "stories",
    "song",
    "songs",
    "deed",
    "deeds",
    "tidings",
    "coming",
    "passing",
    "conquest",
    "conquests",
    "ruin",
    "record",
    "records",
    "legend",
    "legends",
    "myth",
    "myths",
    "history",
    "strife",
    "struggle",
    "glory",
    "downfall",
    "matter",
    "talk",
    "say",
    "rise",
    "making",
    "taking",
    "telling",
    "fate",
    "doom",
    "lament",
    "epic",
    "true",
];
